### PR TITLE
Add support for Google Auth provider

### PR DESCRIPTION
**Pull request by Shivam010**
Add support for Google Auth, so that if one wants to that all Beam members should belong to a Google Workspace, they can use it. 

Use `GOOGLE_ALLOWED_DOMAIN` to restrict Google Login to a workspace domain. But unlike `GITHUB_ALLOWED_ORG` which is required, `GOOGLE_ALLOWED_DOMAIN` is optional

### CODE REVIEW

**Comment by jasonlong** [comment]
Thank you for the contribution @Shivam010. I'll let @bogdansoare review this from a technical standpoint, but we're definitely happy to have more auth options.

One minor thing: would you mind also updating `.env.example` to include the new auth option?

**Comment by Shivam010** [comment]
Yeah sure, thanks @jasonlong for pointing out. I kinda missed the example env file `.env.example`

**Comment by jasonlong** [comment]
Hey @Shivam010, thanks for bearing with us as we figure out our direction going forward. After talking to @bogdansoare, we agreed that we're not going to add any more auth providers as built-in options but rather encourage folks to utilize the NextAuth.js library (which is already in the app) to customize their own auth setup.

I added a note in the README about this, but let us know if you need more info. I'm going to close this for now.

**Comment by Shivam010** [comment]
Thanks for the update. Yeah, I get it, also NextAuth is very easy to set up and customize.

**Pull request closed without merging**
