### PR TITLE
feat: Show the content of a post when notifying Slack

### LINKED ISSUE #47: Show the content of a post when notifying Slack
# Description
Show the content of a post in the Slack message when notifying a Slack channel.

Screen Shot 2022-02-24 at 5 09 30 PM

## Example
Here is an example post on Beam:

Screen Shot 2022-02-24 at 5 10 08 PM

### Current behaviour of the Slack notification
Shows the link, title, and author
Screen Shot 2022-02-24 at 5 09 20 PM

### Proposed behaviour of the Slack notification
Shows the link, title, author, and content
Screen Shot 2022-02-24 at 5 09 30 PM

# Possible solution
Using the https://github.com/instantish/mack package to convert markdown to Slack blocks.

Trade-offs: it adds another dependency, Slack messages will take up more vertical space in the channel.

Alternatives: just show the first few lines of text with an ellipsis, or just preview the images.

### PR DESCRIPTION
**Pull request by marissamarym**
Closes #47

# Demo

## Slack notification
Screen Shot 2022-02-24 at 10 38 49 PM

## Beam post

Screen Shot 2022-02-24 at 10 39 07 PM

# Changes

- Uses the [mack](https://github.com/instantish/mack) (markdown to slack) package to convert Markdown to Slack blocks

### CODE REVIEW

**Comment by jasonlong** [comment]
Hi @marissamarym, thanks for taking the time to implement this and submit a PR. 

For now, we'd prefer to keep the Slack notifications lightweight and simple. Would you be interested in updating your code to generate the same sort of summary snippet that is shown on the listings page? I _think_ it's as simple as pulling the first tag out of the content.

**Comment by marissamarym** [comment]
> Hi @marissamarym, thanks for taking the time to implement this and submit a PR.
> 
> For now, we'd prefer to keep the Slack notifications lightweight and simple. Would you be interested in updating your code to generate the same sort of summary snippet that is shown on the listings page? I _think_ it's as simple as pulling the first tag out of the content.

Sure! I changed it so it just takes the first element and does some light filtering of the elements so it's not previewing the first H1.

Screen Shot 2022-02-24 at 10 36 43 PM


How closely should I match the listings page? I can add filters for the same elements `['p', 'ul', 'ol', 'h3', 'pre', 'img']`. And should I add a `Continue reading >` tag when there's more content?

**Comment by jasonlong** [comment]
Thanks @marissamarym. I think this is great as-is. 

@bogdansoare Would you mind giving this a review before merging? 🙏🏼

**Comment by bogdansoare** [comment]
Hey @marissamarym. Thank you for opening this PR ❤️, adding the summary to the slack notification would be a nice addition.

The only issue that I see is in regards to the dependencies of [mack](https://github.com/instantish/mack), because of the usage of `remark` and `rehype`, the package size is quite big https://bundlephobia.com/package/@instantish/mack@1.1.4.

We decided not use those libraries for markdown and go for [marked](https://github.com/markedjs/marked) because of it's smaller size and speed.

It would be great if you could find an alternative that is either based on `marked` or something smaller in bundle size.

**Comment by marissamarym** [comment]
> Hey @marissamarym. Thank you for opening this PR ❤️, adding the summary to the slack notification would be a nice addition.
> 
> The only issue that I see is in regards to the dependencies of [mack](https://github.com/instantish/mack), because of the usage of `remark` and `rehype`, the package size is quite big https://bundlephobia.com/package/@instantish/mack@1.1.4.
> 
> We decided not use those libraries for markdown and go for [marked](https://github.com/markedjs/marked) because of it's smaller size and speed.
> 
> It would be great if you could find an alternative that is either based on `marked` or something smaller in bundle size.

Sorry for the delay on this, our team is currently working on improving [mack](https://github.com/instantish/mack) as well as some of our other projects to be smaller and use marked. If it works for you, we could close this PR and I'll open another when that's ready

**Comment by jasonlong** [comment]
@marissamarym No worries at all. Feel free to close this and open another anytime. :thumbsup:

**Comment by marissamarym** [comment]
We recently upgraded [mack](https://github.com/instantish/mack) to be ~1/4 the size and it uses `marked` now: https://bundlephobia.com/package/@instantish/mack@1.2.0

**Pull request merged**
