### PR TITLE
version upgrades and trpc v10 syntax

### LINKED ISSUE #81: Update `prisma` dependency to a recent version (4.7.x or higher)
This project is currently using an older version of Prisma. Since it's a popular and useful reference project for using PlanetScale, Prisma and Next.js, I was wondering if it would be possible to upgrade Prisma to the latest version. 

I recommend using Prisma version 4.7.0 or higher since in 4.7.0, the Relation mode feature (previously known as Referential Integrity) went GA. 

You can learn more about this change in the [Prisma Relation mode documentation](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/relation-mode) and [release notes for 4.7.0](https://github.com/prisma/prisma/releases). For further context, this [Pull request](https://github.com/planetscale/docs/pull/223) shows the update made to the PlanetScale docs related to this. 

You can also learn more about upgrading to Prisma version 4 in the [Prisma documentation](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4).

### PR DESCRIPTION
**Pull request by thejessewinton**
This PR is a combined PR from two that I made; all changes are reflected here.

### Updated tRPC syntax to v10
- Better Typescript: the compiler is faster in v10, so it's doing a better job.

- Different naming conventions: uses the current best practives from `create-t3-app`, specifically changing the `trpc` wrapper to be named `api`. Query/mutation hooks are now called as `api.post.like.useMutation()` etc.

- Easier maintainability: along with faster TS, it puts the application in line with the current version of tRPC.

### Upgraded versions of multiple packages to bring beam up-to-date

- The package @instantish/mack, which was being [used here](https://github.com/planetscale/beam/blob/a9e468d918c84065f9df10d96aa28a3a223e2eb2/lib/slack.ts#L23), has been deprected, which would seem to be a part of the problem highlighted in issue #72. The new package that's recommended, [@tryfabric/mack](https://www.npmjs.com/package/@tryfabric/mack) has been rewritten, moving away from `rehype` for parsing to `marked`, and has been updated here.

- Updated `next`, `next-auth`, `react`, `react-dom`, and `@radix-ui/react-tooltip` to fix peer dependency errors that were happening on build. This should also do the work of #75, updating `next-auth` implementation in the code.

- Updated `prisma` and `@prisma/client` and changed the `schema.prisma` to reflect new features. This should serve to fix #81.

I have not had the ability to test all of these updates in a live environment, so please hit me back with feedback/changes.

### CODE REVIEW

**Comment by jasonlong** [comment]
@thejessewinton Thanks so much for the work you've done here. I apologize for the lack of response here. We're currently working to free up some resources to help oversee the maintenance of this repo. My expertise is more on the design side and I'm not the best person to review this work. Hold tight, we'll get to this soon :bow:

**Comment by thejessewinton** [comment]
@jasonlong you got it, glad I could help out!

**Comment by jasonlong** [comment]
I know the build process isn't ideal currently since the Vercel account we're using is part of the PlanetScale org. In the meantime, I can help surface deployment errors.

```
[19:51:00.715] uncaughtException Error: Next.js requires react >= 18.2.0 to be installed.
[19:51:00.715]     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/next@13.2.0_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/dist/build/webpack-config.js:1797:11)
[19:51:00.715]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[19:51:00.715]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[19:51:00.715]     at Module.load (internal/modules/cjs/loader.js:950:32)
[19:51:00.716]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[19:51:00.716]     at Module.require (internal/modules/cjs/loader.js:974:19)
[19:51:00.716]     at require (internal/modules/cjs/helpers.js:101:18)
[19:51:00.716]     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/next@13.2.0_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/dist/build/webpack-build.js:12:46)
[19:51:00.716]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[19:51:00.716]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[19:51:00.720]  ELIFECYCLE  Command failed with exit code 1.
[19:51:00.735] Error: Command "pnpm run build" exited with 1
[19:51:00.823] An error was thrown and it will end the deployment but the thrown error had no message body. Perhaps other parts of the log offer a clue.
```

**Comment by thejessewinton** [comment]
@jasonlong very weird error, React version is fully current, and it’s not something I can replicate locally. Will keep doing some research, but was the error message any more verbose than that?

**Comment by thejessewinton** [comment]
The only other thing I can think is possibly an outdated `package-lock.json`. I'm going to use `pnpm`, create a new lockfile and push.

**Pull request merged**
